Account for overlapping fields in builder (#113)
* Account for overlapping fields in builder

Do not allow overlapping fields to be set at the same time:

```
error[E0599]: no method named `with_middle_bits` found for struct `PartialTestAllowed<false, false, true>` in the current scope
  --> tests/no_compile/overlapping_bitfield_u8_fields.rs:27:47
   |
11 | #[bitfield(u16)]
   | ---------------- method `with_middle_bits` not found for this struct
...
27 |     TestAllowed::builder().with_lower_bits(0).with_middle_bits(0).with_bit_upper(u4::new(0)).build();
   |                                               ^^^^^^^^^^^^^^^^ method not found in `PartialTestAllowed<false, false, true>`
   |
   = note: the method was found for
           - `PartialTestAllowed<bit_upper, false, false>`
help: one of the expressions' fields has a method of the same name
   |
27 |     TestAllowed::builder().with_lower_bits(0).value.with_middle_bits(0).with_bit_upper(u4::new(0)).build();
   |                                               ++++++
```
Account for the set of correct set bitfields on the `build()` restrictions:
```
error[E0599]: no method named `build` found for struct `PartialTestAllowed<true, false, false>` in the current scope
  --> tests/no_compile/overlapping_bitfield_u8_fields.rs:30:55
   |
11 | #[bitfield(u16)]
   | ---------------- method `build` not found for this struct
...
30 |     TestAllowed::builder().with_bit_upper(u4::new(0)).build();
   |                                                       ^^^^^ method not found in `PartialTestAllowed<true, false, false>`
   |
   = note: the method was found for
           - `PartialTestAllowed<true, false, true>`
           - `PartialTestAllowed<true, true, false>`
```

* Loop over field defs only once

* Use bitmask for overlaps check

* Run rustfmt

* remove unnecessary clone

* Do not provide `build` if the resulting value doesn't have all of its bits set

* Deny structs with fields where no valid builder can exist

* Make build valid only in the correct cases

* Properly compute bitmask for array fields

* Account for `u128` bitfields without default where whole range is covered

* Add comment

* Add tests for overlapping fields + range not fully covered