Support setting fields in any order
Change the `Partial*` builder to hold a type parameter per field for the underlying bitfield to track whether a field has been set or not. This allows `.build()` to have better diagnostics:

```
error[E0599]: no method named `build` found for struct `PartialTest<Set_foo, Unset_bar>` in the current scope
  --> tests/no_compile/missing_fields_in_builder.rs:12:33
   |
3  | #[bitfield(u32, default = 0, forbid_overlaps)]
   | ---------------------------------------------- method `build` not found for this struct
...
12 |     Test::builder().with_foo(1).build();
   |                                 ^^^^^ method not found in `PartialTest<Set_foo, Unset_bar>`
   |
   = note: the method was found for
           - `PartialTest<Set_foo, Set_bar>`
```

It also allows the `with_*` methods in any order. These methods can now be called multiple times. We can change the desugaring to force them to only be set once.